version: '3.0'

services:
  mongodb:
    image: mongo
    container_name: twitter-mongodb
    ports:
      - "27017:27017"
  twitter-service:
    build : .
    container_name: twitter-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb
      - SPRING_DATA_MONGODB_DATABASE=tweets